### ISSUE TITLE
Add proper feedback when failing at parsing RDF file

### ISSUE THREAD

**Issue by mboudet** [askomics/flaskomics#322]
```Traceback (most recent call last):
  File "/askomics/askomics/api/file.py", line 246, in get_preview
    res = file.get_preview()
  File "/askomics/askomics/libaskomics/RdfFile.py", line 80, in get_preview
    'location': self.get_location()
  File "/askomics/askomics/libaskomics/RdfFile.py", line 52, in get_location
    graph.parse(self.path, format=self.type_dict[self.type])
  File "/askomics/askomics/libaskomics/RdfGraph.py", line 48, in parse
    self.graph.parse(source=source, publicID=publicID, format=format, location=location, file=file, data=data, **args)```

**Comment by mboudet** [comment]
Should have been fixed by #323
